// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Jun 03 13:40:17 2024

clock_divider clock_divider_inst
(
	.clk_50MHz(clk_50MHz_sig) ,	// input  clk_50MHz_sig
	.rst(rst_sig) ,	// input  rst_sig
	.clk_1kHz(clk_1kHz_sig) ,	// output  clk_1kHz_sig
	.clk_1Hz(clk_1Hz_sig) 	// output  clk_1Hz_sig
);

