// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Fri Jun 07 17:00:50 2024

date_counter date_counter_inst
(
	.rst(rst_sig) ,	// input  rst_sig
	.day_increment(day_increment_sig) ,	// input  day_increment_sig
	.sw7(sw7_sig) ,	// input  sw7_sig
	.year(year_sig) ,	// output [6:0] year_sig
	.month(month_sig) ,	// output [3:0] month_sig
	.day(day_sig) 	// output [4:0] day_sig
);

