// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Jun 03 23:24:33 2024

display_controller display_controller_inst
(
	.clk_1kHz(clk_1kHz_sig) ,	// input  clk_1kHz_sig
	.clk_1Hz(clk_1Hz_sig) ,	// input  clk_1Hz_sig
	.rst(rst_sig) ,	// input  rst_sig
	.hours(hours_sig) ,	// input [4:0] hours_sig
	.minutes(minutes_sig) ,	// input [5:0] minutes_sig
	.seconds(seconds_sig) ,	// input [5:0] seconds_sig
	.year(year_sig) ,	// input [6:0] year_sig
	.month(month_sig) ,	// input [3:0] month_sig
	.day(day_sig) ,	// input [4:0] day_sig
	.Digitron_Out(Digitron_Out_sig) ,	// output [7:0] Digitron_Out_sig
	.DigitronCS_Out(DigitronCS_Out_sig) 	// output [5:0] DigitronCS_Out_sig
);

defparam display_controller_inst._0 = 'b00111111;
defparam display_controller_inst._1 = 'b00000110;
defparam display_controller_inst._2 = 'b01011011;
defparam display_controller_inst._3 = 'b01001111;
defparam display_controller_inst._4 = 'b01100110;
defparam display_controller_inst._5 = 'b01101101;
defparam display_controller_inst._6 = 'b01111101;
defparam display_controller_inst._7 = 'b00000111;
defparam display_controller_inst._8 = 'b01111111;
defparam display_controller_inst._9 = 'b01101111;
