// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Thu Jun 06 19:36:00 2024

time_adjuster time_adjuster_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.switch1(switch1_sig) ,	// input  switch1_sig
	.switch2(switch2_sig) ,	// input  switch2_sig
	.switch3(switch3_sig) ,	// input  switch3_sig
	.switch4(switch4_sig) ,	// input  switch4_sig
	.hours(hours_sig) ,	// inout [4:0] hours_sig
	.minutes(minutes_sig) ,	// inout [5:0] minutes_sig
	.seconds(seconds_sig) ,	// inout [5:0] seconds_sig
	.led_hours(led_hours_sig) ,	// output  led_hours_sig
	.led_minutes(led_minutes_sig) ,	// output  led_minutes_sig
	.led_seconds(led_seconds_sig) 	// output  led_seconds_sig
);

